export const dummyFoodList = [
    { id: "G7f4tq2", foodItemName: "Chicken Biryani", imageSource: "https://foodish-api.com/images/biryani/biryani42.jpg", price: 250 },
    { id: "N5k1zp8", foodItemName: "Mutton Biryani", imageSource: "https://foodish-api.com/images/biryani/biryani68.jpg", price: 300 },
    { id: "D8v3rl6", foodItemName: "Veg Biryani", imageSource: "https://foodish-api.com/images/biryani/biryani22.jpg", price: 200 },
    { id: "R2h5kb1", foodItemName: "Cheese Burger", imageSource: "https://foodish-api.com/images/burger/burger19.jpg", price: 150 },
    { id: "H4t9mc3", foodItemName: "Kebab Burger", imageSource: "https://foodish-api.com/images/burger/burger33.jpg", price: 180 },
    { id: "P7z4xb2", foodItemName: "Double Patty Burger", imageSource: "https://foodish-api.com/images/burger/burger51.jpg", price: 220 },
    { id: "J3t6qh9", foodItemName: "Classic Butter Chicken", imageSource: "https://foodish-api.com/images/butter-chicken/butter-chicken14.jpg", price: 350 },
    { id: "Y1d4gm2", foodItemName: "Spicy Butter Chicken", imageSource: "https://foodish-api.com/images/butter-chicken/butter-chicken4.jpg", price: 360 },
    { id: "F5j2xe6", foodItemName: "Butter Chicken Masala", imageSource: "https://foodish-api.com/images/butter-chicken/butter-chicken11.jpg", price: 340 },
    { id: "K6p1yc3", foodItemName: "Chocolate Dessert", imageSource: "https://foodish-api.com/images/dessert/dessert7.jpg", price: 120 },
    { id: "S8r3qv5", foodItemName: "Fruit Dessert", imageSource: "https://foodish-api.com/images/dessert/dessert29.jpg", price: 110 },
    { id: "Z7h1jx4", foodItemName: "Pastry Dessert", imageSource: "https://foodish-api.com/images/dessert/dessert15.jpg", price: 130 },
    { id: "A2t5vn8", foodItemName: "Plain Dosa", imageSource: "https://foodish-api.com/images/dosa/dosa54.jpg", price: 50 },
    { id: "L3w7bx6", foodItemName: "Masala Dosa", imageSource: "https://foodish-api.com/images/dosa/dosa3.jpg", price: 70 },
    { id: "C9v1nh8", foodItemName: "Cheese Dosa", imageSource: "https://foodish-api.com/images/dosa/dosa48.jpg", price: 80 },
    { id: "M8t2fw1", foodItemName: "Sambhar Idly", imageSource: "https://foodish-api.com/images/idly/idly20.jpg", price: 60 },
    { id: "Q5g4zk2", foodItemName: "Fried Idly", imageSource: "https://foodish-api.com/images/idly/idly50.jpg", price: 70 },
    { id: "B3p8th1", foodItemName: "Cheese Idly", imageSource: "https://foodish-api.com/images/idly/idly8.jpg", price: 80 },
    { id: "T4k5wq9", foodItemName: "Penne Pasta", imageSource: "https://foodish-api.com/images/pasta/pasta12.jpg", price: 150 },
    { id: "E2r7ht3", foodItemName: "Spaghetti Pasta", imageSource: "https://foodish-api.com/images/pasta/pasta27.jpg", price: 170 },
    { id: "F8v1mj5", foodItemName: "Macaroni Pasta", imageSource: "https://foodish-api.com/images/pasta/pasta5.jpg", price: 160 },
    { id: "C5q3fr1", foodItemName: "Margherita Pizza", imageSource: "https://foodish-api.com/images/pizza/pizza65.jpg", price: 200 },
    { id: "H9m2ty4", foodItemName: "Pepperoni Pizza", imageSource: "https://foodish-api.com/images/pizza/pizza15.jpg", price: 250 },
    { id: "N1z6ue3", foodItemName: "BBQ Chicken Pizza", imageSource: "https://foodish-api.com/images/pizza/pizza47.jpg", price: 270 },
    { id: "V7g2hb4", foodItemName: "Steamed Rice", imageSource: "https://foodish-api.com/images/rice/rice11.jpg", price: 60 },
    { id: "J6c4qs2", foodItemName: "Fried Rice", imageSource: "https://foodish-api.com/images/rice/rice30.jpg", price: 120 },
    { id: "T3f8nz5", foodItemName: "Jeera Rice", imageSource: "https://foodish-api.com/images/rice/rice17.jpg", price: 90 },
    { id: "R4y3kp2", foodItemName: "Samosa", imageSource: "https://foodish-api.com/images/samosa/samosa10.jpg", price: 20 },
    { id: "X1p9jx6", foodItemName: "Paneer Tikka Samosa", imageSource: "https://foodish-api.com/images/samosa/samosa5.jpg", price: 40 },
    { id: "L5g1wv8", foodItemName: "Veg Burger", imageSource: "https://foodish-api.com/images/burger/burger77.jpg", price: 100 },
    { id: "K2d4hf1", foodItemName: "Grilled Chicken Burger", imageSource: "https://foodish-api.com/images/burger/burger61.jpg", price: 180 },
    { id: "Q8t1nq7", foodItemName: "Butter Paneer", imageSource: "https://foodish-api.com/images/butter-chicken/butter-chicken6.jpg", price: 250 },
    { id: "D6k3xz2", foodItemName: "Butter Chicken Tikka", imageSource: "https://foodish-api.com/images/butter-chicken/butter-chicken19.jpg", price: 270 },
    { id: "H1p5lv9", foodItemName: "Ice Cream Dessert", imageSource: "https://foodish-api.com/images/dessert/dessert9.jpg", price: 90 },
    { id: "G7t8xy2", foodItemName: "Ghee Roast Dosa", imageSource: "https://foodish-api.com/images/dosa/dosa61.jpg", price: 85 },
    { id: "Y2m4tz1", foodItemName: "Stuffed Masala Dosa", imageSource: "https://foodish-api.com/images/dosa/dosa71.jpg", price: 95 },
    { id: "M3h8re6", foodItemName: "Rava Dosa", imageSource: "https://foodish-api.com/images/dosa/dosa48.jpg", price: 90 },
    { id: "Z4f6jv5", foodItemName: "Mini Idly", imageSource: "https://foodish-api.com/images/idly/idly31.jpg", price: 40 },
    { id: "J1c8sn4", foodItemName: "Pasta Arrabbiata", imageSource: "https://foodish-api.com/images/pasta/pasta23.jpg", price: 160 },
    { id: "F5r2xn7", foodItemName: "Alfredo Pasta", imageSource: "https://foodish-api.com/images/pasta/pasta8.jpg", price: 180 },
    { id: "T3m7pk2", foodItemName: "Tandoori Paneer Pizza", imageSource: "https://foodish-api.com/images/pizza/pizza89.jpg", price: 300 },
    { id: "H8g2wt3", foodItemName: "Garlic Bread Pizza", imageSource: "https://foodish-api.com/images/pizza/pizza37.jpg", price: 220 },
    { id: "P1q4jh6", foodItemName: "Lemon Rice", imageSource: "https://foodish-api.com/images/rice/rice6.jpg", price: 80 },
    { id: "R2k7nz9", foodItemName: "Egg Fried Rice", imageSource: "https://foodish-api.com/images/rice/rice13.jpg", price: 130 },
    { id: "L8v1bg4", foodItemName: "Onion Samosa", imageSource: "https://foodish-api.com/images/samosa/samosa3.jpg", price: 25 },
    { id: "Q3f6pj8", foodItemName: "Veggie Biryani", imageSource: "https://foodish-api.com/images/biryani/biryani33.jpg", price: 230 },
    { id: "T2k8lw7", foodItemName: "Mushroom Burger", imageSource: "https://foodish-api.com/images/burger/burger77.jpg", price: 160 },
    { id: "K1j4dz2", foodItemName: "Classic Spaghetti", imageSource: "https://foodish-api.com/images/pasta/pasta27.jpg", price: 170 },
    { id: "X3q6mv1", foodItemName: "Paneer Tikka Pizza", imageSource: "https://foodish-api.com/images/pizza/pizza47.jpg", price: 280 },
    { id: "Y9f1xq8", foodItemName: "Chettinad Biryani", imageSource: "https://foodish-api.com/images/biryani/biryani55.jpg", price: 280 }
];
