export const dummyFoodItems = [
    { "id": "F1a2b3c", "name": "North Indian", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/North%20Indian.png" },
    { "id": "D4e5f6g", "name": "Pizza", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Pizza.png" },
    { "id": "H7i8j9k", "name": "Burger", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Burger.png" },
    { "id": "L1m2n3o", "name": "Biryani", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Biryani.png" },
    { "id": "P4q5r6s", "name": "Chinese", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Chinese.png" },
    { "id": "T7u8v9w", "name": "Rolls", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Rolls.png" },
    { "id": "X1y2z3a", "name": "Chole Bhature", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Chole%20Bhature.png" },
    { "id": "B4c5d6e", "name": "Dosa", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Dosa.png" },
    { "id": "G7h8i9j", "name": "Paratha", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Paratha.png" },
    { "id": "K1l2m3n", "name": "Pasta", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Pasta.png" },
    { "id": "R4s5t6u", "name": "Cake", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Cake.png" },
    { "id": "Y7z8a9b", "name": "Noodles", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Noodles.png" },
    { "id": "C1d2e3f", "name": "Pav Bhaji", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Pav%20Bhaji.png" },
    { "id": "F4g5h6i", "name": "South Indian", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/South%20Indian.png" },
    { "id": "J7k8l9m", "name": "Salad", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Salad.png" },
    { "id": "N1o2p3q", "name": "Pastry", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Pastry.png" },
    { "id": "T4u5v6w", "name": "Pure Veg", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Pure%20Veg.png" },
    { "id": "X7y8z9a", "name": "Shake", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Shake.png" },
    { "id": "B1c2d3e", "name": "Ice Cream", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Ice%20Cream.png" },
    { "id": "F4g5H6i", "name": "Idli", "imageSrc": "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/PC_Mweb/Idli.png" }
]
